def throws an error {
  throw $GeneralError "An error :)"
}

try {
  throws an error
} catch (tag) {
  GeneralError => {
    print "An error ocurred"
  }
}