def throws an error {
  IOError "An error :)"
}

try {
  throws an error
} catch (err) {
  General => {
    print "An error occurred. The message was:"
    print (err.msg)
  }
  
  * => {
    print (err.tag)
  }
}
