def throws an error {
  throw $GeneralError "An error :)"
}

try {
  throws an error
} catch (err) {
  GeneralError => {
    print "An error occurred. The message was:"
    print (err.msg)
  }
}